import uuid
from datetime import datetime, timezone
from typing import Optional, Any, Dict, List
from pydantic import BaseModel, ConfigDict, Field

from agents.tools.base import ToolResultStatus


class AgentAction(BaseModel):
    """Structured action decision generated by the planner or replanner."""

    tool_name: str = Field(..., description="Registered tool name to invoke")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Typed arguments for tool execution")
    rationale: str = Field(..., description="Operational reason for choosing this action")
    expected_outcome: Optional[str] = Field(None, description="Anticipated effect of executing this tool")


class AgentObservation(BaseModel):
    """Structured observation captured after tool execution."""

    tool_name: str = Field(..., description="Tool that produced this observation")
    status: ToolResultStatus = Field(..., description="Result status returned by the tool")
    data: Optional[Any] = Field(None, description="Observation payload returned by tool")
    message: str = Field(..., description="Descriptive status message")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when observation was captured",
    )


class AgentPlanStep(BaseModel):
    """Individual planned milestone within the agent's current plan."""

    step_number: int
    description: str
    tool_name: str
    status: str = Field("pending", description="pending, completed, failed, adapted")
    parameters: Optional[Dict[str, Any]] = None


class AgentState(BaseModel):
    """Explicit runtime state maintained by the agent during case resolution."""

    # Task identity
    case_id: uuid.UUID
    customer_id: uuid.UUID
    order_id: Optional[uuid.UUID] = None
    customer_goal: str
    issue_type: str

    # Case lifecycle state
    current_status: str = Field("open", description="investigating, planning, executing, verifying, replanning, awaiting_approval, resolved, escalated, failed")
    current_plan: List[Dict[str, Any]] = Field(default_factory=list, description="Serialized list of plan steps")
    current_step: Optional[str] = Field(None, description="Label of current execution step")

    # Risk and approval gates
    risk_level: str = Field("low", description="low, medium, high")
    requires_approval: bool = False
    approval_status: str = Field("not_required", description="not_required, pending, approved, rejected")

    # Knowledge / Evidence gathered
    evidence: Dict[str, Any] = Field(
        default_factory=lambda: {
            "customer": None,
            "order": None,
            "shipment": None,
            "inventory": {},
            "policy": None,
            "alternative_inventory": None,
        },
        description="Structured verified facts gathered during investigation",
    )

    # Observation history
    observations: List[AgentObservation] = Field(default_factory=list)
    tool_history: List[Dict[str, Any]] = Field(default_factory=list)

    # Execution bounds and counters
    attempt_count: int = 0
    replan_count: int = 0
    same_tool_counts: Dict[str, int] = Field(default_factory=dict)
    last_tool: Optional[str] = None
    last_result: Optional[Dict[str, Any]] = None

    # Resolution and verification tracking
    resolution_type: Optional[str] = None
    resolution_status: Optional[str] = None
    verification_status: Optional[str] = None
    failure_reason: Optional[str] = None


class AgentRunResult(BaseModel):
    """Structured summary of the complete autonomous agent execution."""

    success: bool
    case_id: uuid.UUID
    status: str = Field(..., description="Final case status: resolved, awaiting_approval, escalated, failed")
    resolution_status: Optional[str] = None
    requires_approval: bool = False
    current_step: Optional[str] = None
    final_outcome: str = Field(..., description="High-level narrative of the resolution outcome")
    reason: Optional[str] = None
    steps_executed: int = 0
    replans: int = 0
    execution_trace: List[Dict[str, Any]] = Field(default_factory=list)
